name: Integration tests

env:
  UPDATE_RELEASE_TITLE: 'update-existing-release'
  UPDATE_RELEASE_DESCRIPTION: 'We eat our own dogfood here. We use update-existing-release to release update-existing-release, to prove that it works on all targets.'

on:
  push:
    branches:
      main

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create release
        uses: altavec/update-existing-release@v1
  ci:
    name: Continuous integration
    needs: create
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:   
      - name: Install gnuwin32 and zip on Windows
        if: startsWith(matrix.os, 'windows')
        run: choco install gnuwin32-coreutils.install zip

      - uses: actions/checkout@v4

      - name: Build bundle with npm
        run: |
          npm install
          npm run bundle

      - name: Zip distribution
        run: |
          zip -9 update-existing-release-${{ matrix.os }}.zip *
          zip -9 -r update-existing-release-${{ matrix.os }}.zip src dist img .github

      - name: Update release
        uses: altavec/update-existing-release@v1
        with:
          files: update-existing-release-${{ matrix.os }}.zip
